server:
  port: 9090
spring:
  application:
    name: HYSTRIX
turbine:
  aggregator:
    clusterConfig: DEFAULT
  appConfig: USER-SERVICE,CLIENT-SERVICE
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka.k8s.com/eureka/
  instance:
    preferIpAddress: false
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
