server:
  port: 9090
spring:
  application:
    name: HYSTRIX
turbine:
  appConfig: USER-SERVICE,CLIENT-SERVICE
  clusterNameExpression: "'default'"
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: false
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
